[versions]
accompanist = "0.36.0"
activity-compose = "1.12.3"
agp = "9.0.0"
androidx-test-ext-junit = "1.3.0"
ben-manes-versions = "0.53.0"
camera-x = "1.5.3"
cardview = "1.0.0"
coil-compose = "2.7.0"
compose-bom = "2026.01.01"
compose-html = "1.0.2"
compressor = "3.0.1"
constraintlayout = "2.2.1"
constraintlayout-compose = "1.1.1"
converter-moshi = "3.0.0"
core-ktx = "1.17.0"
core-splashscreen = "1.2.0"
core-testing = "2.2.0"
desugar-jdk-libs = "2.1.5"
detekt = "1.23.8"
espresso-core = "3.7.0"
firebase-bom = "34.9.0"
fragment-compose = "1.8.9"
google-material = "1.13.0"
google-services = "4.4.4"
hilt-android = "2.59.1"
hilt-navigation-compose = "1.3.0"
junit = "4.13.2"
kotlin = "2.3.10"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines-test = "1.10.2"
kotlin-serialization = "1.10.0"
ksp = "2.3.4"
ktlint = "14.0.1"
leakcanary-android = "2.14"
lifecycle = "2.10.0"
mapbox-navigation = "3.4.0-beta.1"
mockk = "1.14.9"
moshi = "1.15.2"
navigation-compose = "2.9.7"
okhttp-bom = "5.3.2"
paparazzi = "2.0.0-alpha02"
play-services-location = "21.3.0"
retrofit = "3.0.0"
robolectric = "4.16.1"
room = "2.8.4"
timber = "5.0.1"
ui-viewbinding = "1.10.2"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera-x" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera-x" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera-x" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera-x" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera-x" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment-compose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "ui-viewbinding" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-html = { module = "com.github.ireward:compose-html", version.ref = "compose-html" }
compressor = { module = "id.zelory:compressor", version.ref = "compressor" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
mapbox-navigation-android = { module = "com.mapbox.navigationcore:android", version.ref = "mapbox-navigation" }
mapbox-navigation-ui-components = { module = "com.mapbox.navigationcore:ui-components", version.ref = "mapbox-navigation" }
material = { module = "com.google.android.material:material", version.ref = "google-material" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp-bom" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidxRoom = { id = "androidx.room", version.ref = "room" }
benManesversions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
